### ISSUE TITLE
Refactor WindowFractalCode.py into SlidingWindow class

### ISSUE THREAD

**Issue by ndusek** [amdenton/SlidingWindows#2]
@dave05 @amdenton I created a [branch](https://github.com/amdenton/SlidingWindows/tree/original_code) to work on the following:

- [x] Create SlidingWindow class and migrate/refactor methods from WindowFractalCode.py
- [x] Modify test to reference SlidingWindow class (logic should remain the same)
- [x] Create a test data file with URLs where the necessary test images can be downloaded

I'm already working on these items, but just wanted to track it so everyone's up to date.

**Comment by dave05** [comment]
Perfect. This great idea. To follow basic Software Development Principle, let's start by drawing some UMLs like Class Diagram.

**Comment by DebuggerDave** [comment]
SlidingWindow class, unit test file, and image generator file created. No images are downloaded.
